vscode:
    extensions:
        - GitHub.copilot
        - oderwat.indent-rainbow
        - ZainChen.json
        - ms-python.python
        - ms-azuretools.vscode-docker
        - VisualStudioExptTeam.vscodeintellicode
        - esbenp.prettier-vscode
