vscode:
    extensions:
        - oderwat.indent-rainbow
        - ZainChen.json
        - ms-python.python
        - ms-azuretools.vscode-docker
        - VisualStudioExptTeam.vscodeintellicode
        - esbenp.prettier-vscode
tasks:
  # many tasks will run in parallel or use "gp sync-await and gp sync-done."
  - name: Install poetry and dependencies, then export libraries and use pip to install them
    before: curl -sSL https://install.python-poetry.org | python3 -
    command: >
      poetry install --no-root && 
      poetry export -f requirements.txt --output requirements.txt && 
      pip install -r requirements.txt && 
      rm requirements.txt
