name: Release to Docker Hub

on:
  release:
    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: Prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_STEVE_USERNAME }}
          password: ${{ secrets.DOCKER_STEVE_ACCESS_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . 
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: |
            ${{ secrets.DOCKER_STEVE_USERNAME }}/srt-translator:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKER_STEVE_USERNAME }}/srt-translator:latest
      
      - name: Logout from Docker Hub
        run: docker logout