name: Release to Docker Hub

on:
  release:
    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: Prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_STEVE_USERNAME }}
          password: ${{ secrets.DOCKER_STEVE_ACCESS_TOKEN }}
      
      - name: Build and push srt-translator cli
        uses: docker/build-push-action@v6
        with:
          context: . 
          file: dockerfile
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: |
            ${{ secrets.DOCKER_STEVE_USERNAME }}/srt-translator:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKER_STEVE_USERNAME }}/srt-translator:latest

      - name: Build and push srt-translator daemon
        uses: docker/build-push-action@v6
        with:
          context: . 
          file: dockerfile-daemon
          platforms: linux/amd64,linux/arm64
          push: true 
          tags: |
            ${{ secrets.DOCKER_STEVE_USERNAME }}/srt-translator-daemon:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKER_STEVE_USERNAME }}/srt-translator-daemon:latest
      
      - name: Logout from Docker Hub
        run: docker logout